export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_ARTICLES = 'FILTER_ARTICLES'

export const FILTER_BY_DATE = 'FILTER_BY_DATE'

export const FILTER_BY_NAME = 'FILTER_BY_NAME'
